// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAboUWNv9POnz3Hka33WlXKgZlxZTLBgGM',
    appId: '1:458197825311:web:f6b02b71923fb4f1e3a22a',
    messagingSenderId: '458197825311',
    projectId: 'swbank-75fbd',
    authDomain: 'swbank-75fbd.firebaseapp.com',
    storageBucket: 'swbank-75fbd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWL9AxUTAkedrhCjsYUxXwi6k_htS4ADw',
    appId: '1:458197825311:android:d1986e1dfd68c32ce3a22a',
    messagingSenderId: '458197825311',
    projectId: 'swbank-75fbd',
    storageBucket: 'swbank-75fbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2aKAGjJO7IRiLn-RphwebDBXmb7Cwij8',
    appId: '1:458197825311:ios:d8c551c0a9e53d33e3a22a',
    messagingSenderId: '458197825311',
    projectId: 'swbank-75fbd',
    storageBucket: 'swbank-75fbd.appspot.com',
    iosBundleId: 'com.example.swbanking',
  );
}
